# Generated by Django 5.2.4 on 2025-08-14 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_publication_date_post_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
