# Generated by Django 5.2.4 on 2025-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
