# Generated by Django 5.2.4 on 2025-08-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('es_usuario', models.BooleanField(default=False)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.CharField(choices=[('agradecimiento', 'Agradecimiento'), ('reclamo', 'Reclamo'), ('opinion', 'Opinión libre'), ('bloqueado', 'Usuario bloqueado'), ('colaborador', 'Quiero ser colaborador'), ('reporte', 'Reporte de usuario')], max_length=20)),
                ('mensaje', models.TextField(max_length=400)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
