# Generated by Django 5.2.4 on 2025-07-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, max_length=200, null=True, upload_to='avatars/'),
        ),
    ]
