# Generated by Django 5.2.4 on 2025-08-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.png', max_length=200, null=True, upload_to='avatars/'),
        ),
    ]
