# Generated by Django 5.2.4 on 2025-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('localidad', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
